# export UID=`id -u`; export GID=`id -g`; docker-compose up -d dev

version: "3.3"

services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    tty: True
    user: $UID:$GID:$USER
    volumes:
      - $MYREPOS/Mohid:/source/Mohid
      - $MYREPOS/docker-mohid:/tmp/tests
    working_dir: /source/Mohid/

