# export UID=`id -u`; export GID=`id -g`; docker-compose up -d dev

version: "3.3"

services:

  # using system libraries (doesn't work because it enforces argument matching)
  system:
    build:
      context: .
      dockerfile: Dockerfile.system
    tty: True
    user: $UID:$GID:$USER
    volumes:
      - $MYREPOS/Mohid:/tmp/Mohid
      - $MYREPOS/docker-mohid:/tmp/docker-mohid

  # statically compile only the specific libraries (hdf5, netcdf, fproj)
  # that need recompiling with -w -fallow-argument-mismatch -O2
  static:
    build:
      context: .
      dockerfile: Dockerfile.static1
    tty: True
    user: $UID:$GID:$USER
    volumes:
      - $MYREPOS/Mohid:/tmp/Mohid
      - $MYREPOS/docker-mohid:/tmp/docker-mohid

  # dynamic compile everything
  dynamic:
    build:
      context: .
      dockerfile: Dockerfile.dynamic
    tty: True
    user: $UID:$GID:$USER
    volumes:
      - $MYREPOS/Mohid:/tmp/Mohid
      - $MYREPOS/docker-mohid:/tmp/docker-mohid

